server:
  port: 8081

spellchain:
  min-players: 2
  max-players: 4
  allowed-punctuation: "-'/ ."
  dictionary-jdbc-url: "jdbc:sqlite:./data/wiktionary_english_dictionary.sqlite"
  allowed-origins: "https://spellchain.mattisschulte.io"

spring:
  jackson:
    serialization:
      INDENT_OUTPUT: false